### ISSUE TITLE
Metal Slug 3 no video

### ISSUE THREAD

**Issue by hargtholan** [lantus/mame-nx#12]
Can hear that it plays sounds, but screen is black. Can hear how I insert coins and start playing.

**Comment by lantus** [comment]
yep looks like no neogeo roms have working video . checking into it

**Comment by hargtholan** [comment]
Actually some work, Metal Slug and Metal Slug X for instance. But they have another issue. Could be same root cause?

**Comment by snoofly** [comment]
asteroid seems to suffer same issue so not sure just related to neogeo but perhaps vector games as well — bzone gravitar tempest all have same issue

**Comment by lantus** [comment]
fixed in 31067dcb11afce3e2d923e0e19569c946f206837
