### ISSUE TITLE
Flickering vertical black bar

### ISSUE THREAD

**Issue by hargtholan** [lantus/mame-nx#14]
Does not happen always even with the same game. Sometimes game works fine and sometimes a vertical wide black bar (sometimes two) is displayed. it is like dancing a bit and moving a bit across the screen. Can be seen in "Metal Slug". Not sure yet is it only in NeoGeo games.

**Comment by hargtholan** [comment]
Also in "Bomber Man World (World)"

**Comment by hargtholan** [comment]
Happens also with "Black Dragon" and as said, sometimes only. the black bar is typically on the right side of the screen and it wobbles.

**Comment by snoofly** [comment]
arabian rom suffers from this also

**Comment by lantus** [comment]
confirmed. if its the first ROM you load it appears to work, but any subsequent roms you load after the first one the bar appears

**Comment by hargtholan** [comment]
Oh good finding. Perhaps just need to re-init stuff? Sounds like easy to fix.

**Comment by lantus** [comment]
yeah its how im cleaning up/re-initing OpenGL. will work on a fix

**Comment by lantus** [comment]
fixed in 2.2  -  https://github.com/lantus/mame-nx/releases/tag/2.2
