### ISSUE TITLE
Random crashes when starting up

### ISSUE THREAD

**Issue by hargtholan** [lantus/mame-nx#15]
I've got firmware 4.0.1.
ReiNX 1.7, hbmenu latest also, latest tinfoil release.
It randomly crashes when starting up Mame-nx with Error code: 2168-0002

I guess that 50% of the times I try to launch it.

Is there any debug info? coredumps or stuff? logs? How can we know where and why is it crashing?

**Comment by lantus** [comment]
do you mean when you load a rom or just to the menu?

**Comment by hargtholan** [comment]
Actually both

**Comment by Saiga89** [comment]
I get crashes on certain games for sure. The Turtles in Time rom I got for example. It works, but then sometimes just randomly says NOPE. lol I stopped playing it because it kept making me have to relaunch my CW & all. I am on Switch 6.0.1 though.

**Comment by lantus** [comment]
> I get crashes on certain games for sure. The Turtles in Time rom I got for example. It works, but then sometimes just randomly says NOPE. lol I stopped playing it because it kept making me have to relaunch my CW & all. I am on Switch 6.0.1 though.

what CFW are you booting into?

**Comment by lantus** [comment]
try the latest build https://github.com/lantus/mame-nx/releases/tag/2.2  it should be much more stable now. 👍
