### ISSUE TITLE
Can't compilte - nx_display.o error

### ISSUE THREAD

**Issue by SUPER-DAN** [lantus/mame-nx#3]
Hi, 

Thanks for this great work.

However, I can't compile on my own your work using "make", original(untouch clone) or modified by me.  It always stops at nx_display.o (after a good 4-5 minutes in the process, I have a i7 6700K).  I have downloaded all dependencies as you mentioned, but there might missing some that were not listed I am not too sure.  It looks like this : 

In file included from C:/devkitPro/libnx/include/switch.h:91,
                 from src/nx/nx_display.c:9:
C:/devkitPro/libnx/include/switch/runtime/env.h:19:34: error: macro "BIT" requires 2 arguments, but only 1 given
     EntryFlag_IsMandatory = BIT(0), ///< Specifies that the entry **must** be processed by the homebrew application.
                                  ^
make: *** [makefile:268: obj/mame/nx/nx_display.o] Error

I just wanted to add ZL and ZR as an option for the buttons as they are not available.  I have tried from a Windows and Mac...

Here is the output of packages available and installed in devpro

msys apr 1.6.3-1
msys apr-devel 1.6.3-1
msys apr-util 1.6.1-1
msys apr-util-devel 1.6.1-1
msys asciidoc 8.6.10-1
msys aspell 0.60.6.1-1
msys aspell-devel 0.60.6.1-1
msys aspell6-en 2018.04.16-1
msys atool 0.39.0-1
msys autoconf 2.69-5 [installed]
msys autoconf-archive 2017.09.28-1
msys autoconf2.13 2.13-2
msys autogen 5.18.12-2
msys automake-wrapper 11-1 [installed]
msys automake1.10 1.10.3-3 [installed]
msys automake1.11 1.11.6-3 [installed]
msys automake1.12 1.12.6-3 [installed]
msys automake1.13 1.13.4-4 [installed]
msys automake1.14 1.14.1-3 [installed]
msys automake1.15 1.15.1-1 [installed]
msys automake1.16 1.16.1-1 [installed]
msys automake1.6 1.6.3-2 [installed]
msys automake1.7 1.7.9-2 [installed]
msys automake1.8 1.8.5-3 [installed]
msys automake1.9 1.9.6-2 [installed]
msys axel 2.16.1-1
msys bash 4.4.019-3 [installed]
msys bash-completion 2.8-2 [installed]
msys bash-devel 4.4.019-3
msys bc 1.07.1-1
msys binutils 2.30-1
msys bison 3.0.5-1
msys bisonc++ 6.02.01-1
msys brotli 1.0.5-2 [installed]
msys brotli-devel 1.0.5-2
msys brotli-testdata 1.0.5-2
msys bsdcpio 3.3.3-3 [installed]
msys bsdtar 3.3.3-3 [installed]
msys busybox 1.23.2-1
msys bzip2 1.0.6-2 [installed]
msys bzr 2.7.0-2
msys bzr-fastimport 0.13.0-1
msys ca-certificates 20170717-2 [installed]
msys ccache 3.4.3-1
msys cdecl 2.5-1
msys cgdb 0.7.0-1
msys clang-svn 60106.1d5b05f-1
msys cloc 1.72-1
msys cloog 0.19.0-2
msys cloog-devel 0.19.0-2
msys cmake 3.12.1-1
msys cocom 0.996-2
msys colordiff 1.0.18-1
msys colormake-git r8.9c1d2e6-1
msys conemu-git r3330.34a88ed-1
msys coreutils 8.26-3 [installed]
msys cpio 2.12-1
msys crosstool-ng 1.23.0-2
msys crosstool-ng-git 1.19.314.a483cd9-1
msys cscope 15.9-1
msys ctags 5.8-2
msys curl 7.61.0-2 [installed]
msys cvs 1.11.23-2
msys cygrunsrv 1.62-1
msys cyrus-sasl 2.1.27rc8-1
msys dash 0.5.10.2-1 [installed]
msys db 5.3.28-2 [installed]
msys db-docs 5.3.28-2
msys dejagnu 1.6.1-1
msys delta 20060803-1
msys depot-tools-git r2542.77b74b5-1
msys dialog 1.3_20180621-1
msys diffstat 1.61-1
msys diffutils 3.6-1 [installed]
msys docbook-dsssl 1.79-1
msys docbook-mathml 1.1CR1-1
msys docbook-sgml 4.5-1
msys docbook-sgml31 3.1-1
msys docbook-xml 4.5-2
msys docbook-xsl 1.79.2-1
msys docx2txt 1.4-1
msys dos2unix 7.4.0-1
msys doxygen 1.8.14-1
msys dtc 1.4.7-1 [installed]
msys easyoptions-git r37.c481763-1
msys ed 1.14.2-1
msys elinks-git 0.13.4008.f86be659-1
msys emacs 25.2-3
msys expat 2.2.5-1
msys expect 5.45.4-2
msys fcode-utils 1.0.2-1
msys file 5.34-1 [installed]
msys filesystem 2018.08-1 [installed]
msys findutils 4.6.0-1 [installed]
msys fish 2.7.1-2
msys flex 2.6.4-1 [installed]
msys flexc++ 2.07.02-1
msys fzy 0.9-1
msys gamin 0.1.10-3
msys gamin-devel 0.1.10-3
msys gamin-python 0.1.10-3
msys gawk 4.2.1-1 [installed]
msys gcc 7.3.0-3
msys gcc-fortran 7.3.0-3
msys gcc-libs 7.3.0-3 [installed]
msys gdb 7.12.1-1
msys gdbm 1.16-1 [installed]
msys gengetopt 2.22.6-3
msys getent 2.18.90-2 [installed]
msys getopt 1.1.6-1
msys gettext 0.19.8.1-1 [installed]
msys gettext-devel 0.19.8.1-1
msys git 2.19.0-1
msys git-bzr-ng-git r61.9878a30-1
msys git-extras-git 4.3.0-1
msys git-flow 1.11.0-1
msys glib2 2.54.3-1 [installed]
msys glib2-devel 2.54.3-1
msys glib2-docs 2.54.3-1
msys global 6.6.2-1
msys gmp 6.1.2-1 [installed]
msys gmp-devel 6.1.2-1
msys gnome-doc-utils 0.20.10-1
msys gnu-netcat 0.7.1-1
msys gnupg 2.2.9-1 [installed]
msys gnutls 3.6.3-1
msys gperf 3.1-1
msys gradle 4.10-1
msys gradle-doc 4.10-1
msys grep 3.1-1 [installed]
msys grml-zsh-config 0.14.2-1
msys groff 1.22.3-1
msys gtk-doc 1.28-1
msys guile 2.2.4-1
msys gyp-git r2114.a2738d85-1
msys gzip 1.9-1 [installed]
msys heimdal 7.5.0-2
msys heimdal-devel 7.5.0-2
msys heimdal-libs 7.5.0-2 [installed]
msys help2man 1.47.6-1
msys hexcurse 1.60.0-1
msys icmake 9.02.08-1
msys icon-naming-utils 0.8.90-1
msys icu 62.1-1 [installed]
msys icu-devel 62.1-1
msys idutils 4.6-2
msys inetutils 1.9.4-1 [installed]
msys info 6.5-2 [installed]
msys intltool 0.51.0-2
msys iperf 2.0.12-1
msys iperf3 3.6-2
msys irssi 1.1.1-1
msys isl 0.19-1
msys isl-devel 0.19-1
msys itstool 2.0.4-2
msys jansson 2.11-1
msys jansson-devel 2.11-1
msys jhbuild-git 9425.76669ac0-1
msys jsoncpp 1.8.4-1
msys jsoncpp-devel 1.8.4-1
msys lemon 3.21.0-1
msys less 530-1 [installed]
msys lftp 4.8.4-1
msys libarchive 3.3.3-3 [installed]
msys libarchive-devel 3.3.3-3
msys libargp 20110921-1 [installed]
msys libargp-devel 20110921-1
msys libasprintf 0.19.8.1-1 [installed]
msys libassuan 2.5.1-1 [installed]
msys libassuan-devel 2.5.1-1
msys libatomic_ops-devel 7.6.0-1
msys libbobcat 4.08.03-1
msys libbobcat-devel 4.08.03-1
msys libbz2 1.0.6-2 [installed]
msys libbz2-devel 1.0.6-2
msys libcares 1.14.0-1
msys libcares-devel 1.14.0-1
msys libcrypt 2.1-2 [installed]
msys libcrypt-devel 2.1-2
msys libcurl 7.61.0-2 [installed]
msys libcurl-devel 7.61.0-2
msys libdb 5.3.28-2 [installed]
msys libdb-devel 5.3.28-2
msys libedit 3.1-20170329 [installed]
msys libedit-devel 3.1-20170329
msys libelf 0.8.13-2
msys libelf-devel 0.8.13-2
msys libevent 2.1.8-1
msys libevent-devel 2.1.8-1
msys libexpat 2.2.5-1 [installed]
msys libexpat-devel 2.2.5-1
msys libffi 3.2.1-3 [installed]
msys libffi-devel 3.2.1-3
msys libgc 7.6.0-1
msys libgc-devel 7.6.0-1
msys libgcrypt 1.8.3-2 [installed]
msys libgcrypt-devel 1.8.3-2
msys libgdbm 1.16-1 [installed]
msys libgdbm-devel 1.16-1
msys libgettextpo 0.19.8.1-1 [installed]
msys libgnutls 3.6.3-1 [installed]
msys libgnutls-devel 3.6.3-1
msys libgpg-error 1.32-1 [installed]
msys libgpg-error-devel 1.32-1
msys libgpgme 1.11.1-1 [installed]
msys libgpgme-devel 1.11.1-1
msys libgpgme-python2 1.11.1-1
msys libgpgme-python3 1.11.1-1
msys libguile 2.2.4-1
msys libguile-devel 2.2.4-1
msys libhogweed 3.4-1 [installed]
msys libiconv 1.15-1 [installed]
msys libiconv-devel 1.15-1
msys libidn 1.35-1
msys libidn-devel 1.35-1
msys libidn2 2.0.5-1 [installed]
msys libidn2-devel 2.0.5-1
msys libintl 0.19.8.1-1 [installed]
msys libksba 1.3.5-1 [installed]
msys libksba-devel 1.3.5-1
msys libltdl 2.4.6-4 [installed]
msys liblz4 1.8.2-1 [installed]
msys liblz4-devel 1.8.2-1
msys liblzma 5.2.4-1 [installed]
msys liblzma-devel 5.2.4-1
msys liblzo2 2.10-2 [installed]
msys liblzo2-devel 2.10-2
msys libmetalink 0.1.3-2 [installed]
msys libmetalink-devel 0.1.3-2
msys libneon 0.30.2-1
msys libneon-devel 0.30.2-1
msys libnettle 3.4-1 [installed]
msys libnettle-devel 3.4-1
msys libnghttp2 1.30.0-1 [installed]
msys libnghttp2-devel 1.30.0-1
msys libnpth 1.6-1 [installed]
msys libnpth-devel 1.6-1
msys libopenssl 1.0.2.o-1 [installed]
msys libp11-kit 0.23.9-1 [installed]
msys libp11-kit-devel 0.23.9-1
msys libpcre 8.42-1 [installed]
msys libpcre16 8.42-1 [installed]
msys libpcre2_16 10.31-1
msys libpcre2_32 10.31-1
msys libpcre2_8 10.31-1
msys libpcre2posix 10.31-1
msys libpcre32 8.42-1 [installed]
msys libpcrecpp 8.42-1 [installed]
msys libpcreposix 8.42-1 [installed]
msys libpipeline 1.5.0-1
msys libpipeline-devel 1.5.0-1
msys libpsl 0.20.2-1 [installed]
msys libpsl-devel 0.20.2-1
msys libqrencode-git v3.4.3.r243.g1ef82bd-1
msys libreadline 7.0.005-1 [installed]
msys libreadline-devel 7.0.005-1
msys librhash 1.3.6-1
msys librhash-devel 1.3.6-1
msys libsasl 2.1.27rc8-1
msys libsasl-devel 2.1.27rc8-1
msys libserf 1.3.9-2
msys libserf-devel 1.3.9-2
msys libsqlite 3.21.0-4 [installed]
msys libsqlite-devel 3.21.0-4
msys libssh2 1.8.0-1 [installed]
msys libssh2-devel 1.8.0-1
msys libtasn1 4.13-1 [installed]
msys libtasn1-devel 4.13-1
msys libtirpc 0.2.5-1
msys libtirpc-devel 0.2.5-1
msys libtool 2.4.6-4 [installed]
msys libtre-devel-git 0.8.0.128.6fb7206-1
msys libtre-git 0.8.0.128.6fb7206-1
msys libunistring 0.9.10-1 [installed]
msys libunistring-devel 0.9.10-1
msys libunrar 5.6.6-1
msys libunrar-devel 5.6.6-1
msys libutil-linux 2.26.2-1 [installed]
msys libutil-linux-devel 2.26.2-1
msys libuv 1.23.0-1
msys libuv-devel 1.23.0-1
msys libxml2 2.9.8-1 [installed]
msys libxml2-devel 2.9.8-1
msys libxml2-python 2.9.8-1
msys libxslt 1.1.32-1 [installed]
msys libxslt-devel 1.1.32-1
msys libxslt-python 1.1.32-1
msys libyaml 0.1.7-1
msys libyaml-devel 0.1.7-1
msys lld-svn 4595.3511ec1-1
msys llvm-svn 124592.2aebced-1
msys lndir 1.0.3-1 [installed]
msys lz4 1.8.2-1
msys lzip 1.20-1 [installed]
msys m4 1.4.18-2 [installed]
msys make 4.2.1-1 [installed]
msys make-git 4.1.8.g292da6f-1
msys man-db 2.8.4-1
msys man-pages-posix 2013_a-1
msys markdown 1.0.1-1
msys mc 4.8.20-1
msys mercurial 4.7.1-1
msys mingw-w64-cross-binutils 2.30-1
msys mingw-w64-cross-crt-git 6.0.0.5223.7f9d8753-1
msys mingw-w64-cross-gcc 7.3.0-2
msys mingw-w64-cross-headers-git 6.0.0.5223.7f9d8753-1
msys mingw-w64-cross-tools-git 6.0.0.5141.696b37c3-1
msys mingw-w64-cross-windows-default-manifest 6.4-2
msys mingw-w64-cross-winpthreads-git 6.0.0.5142.0b647fe7-1
msys mingw-w64-cross-winstorecompat-git 6.0.0.5099.5e5f06f6-1
msys mingw-w64-cross-zlib 1.2.11-1
msys mintty 1~2.9.0-1 [installed]
msys mksh 56.c-1
msys moreutils 0.62-1
msys mosh 1.3.2-2
msys mpc 1.1.0-1
msys mpc-devel 1.1.0-1
msys mpdecimal 2.4.2-2
msys mpdecimal-devel 2.4.2-2
msys mpfr 4.0.1-1 [installed]
msys mpfr-devel 4.0.1-1
msys msys2-keyring r9.397a52e-1 [installed]
msys msys2-launcher-git 0.3.32.56c2ba7-2 [installed]
msys msys2-runtime 2.11.1-2 [installed]
msys msys2-runtime-devel 2.11.1-2
msys msys2-w32api-headers 6.0.0.5223.7f9d8753-1
msys msys2-w32api-runtime 6.0.0.5223.7f9d8753-1
msys mutt 1.10.0-2
msys nano 2.9.8-1
msys nano-syntax-highlighting-git 299.5e776df-1
msys nasm 2.13.03-1
msys ncurses 6.1.20180908-1 [installed]
msys ncurses-devel 6.1.20180908-1
msys nettle 3.4-1 [installed]
msys nghttp2 1.30.0-1
msys openbsd-netcat 1.190-2
msys openssh 7.6p1-2
msys openssl 1.0.2.o-1 [installed]
msys openssl-devel 1.0.2.o-1
msys p11-kit 0.23.9-1 [installed]
msys p7zip 16.02-1
msys pacman 5.1.1-2 [installed]
msys pacman-mirrors 20180604-2 [installed]
msys pactoys-git r2.07ca37f-1 [installed]
msys parallel 20180722-1
msys pass 1.7.1-1
msys patch 2.7.6-1
msys patchutils 0.3.4-1
msys pax-git 20161104.2-1 [installed]
msys pcre 8.42-1 [installed]
msys pcre-devel 8.42-1
msys pcre2 10.31-1
msys pcre2-devel 10.31-1
msys perl 5.28.0-1 [installed]
msys perl-Algorithm-Diff 1.1903-1
msys perl-Archive-Zip 1.60-1
msys perl-Authen-SASL 2.16-2
msys perl-Benchmark-Timer 0.7107-1
msys perl-Capture-Tiny 0.46-1
msys perl-Carp-Clan 6.06-1
msys perl-Compress-Bzip2 2.26-2
msys perl-Convert-BinHex 1.125-1
msys perl-Crypt-SSLeay 0.73_06-2
msys perl-DBI 1.641-1
msys perl-Date-Calc 6.4-1
msys perl-Digest-HMAC 1.03-2
msys perl-Digest-MD4 1.9-3
msys perl-Encode-Locale 1.05-1
msys perl-Encode-compat 0.07-1
msys perl-Error 0.17026-1
msys perl-Exporter-Lite 0.08-1
msys perl-Exporter-Tiny 1.002001-1
msys perl-ExtUtils-Depends 0.405-1
msys perl-ExtUtils-MakeMaker 7.34-1
msys perl-ExtUtils-PkgConfig 1.16-1
msys perl-File-Copy-Recursive 0.44-1
msys perl-File-Listing 6.04-2
msys perl-File-Next 1.16-1
msys perl-File-Which 1.22-1
msys perl-Font-TTF 1.06-1
msys perl-Getopt-ArgvFile 1.11-1
msys perl-Getopt-Tabular 0.3-1
msys perl-HTML-Parser 3.72-3
msys perl-HTML-Tagset 3.20-2
msys perl-HTTP-Cookies 6.04-1
msys perl-HTTP-Daemon 6.01-2
msys perl-HTTP-Date 6.02-2
msys perl-HTTP-Message 6.18-1
msys perl-HTTP-Negotiate 6.01-2
msys perl-IO-HTML 1.001-1
msys perl-IO-Socket-INET6 2.72-4
msys perl-IO-Socket-SSL 2.056-1
msys perl-IO-String 1.08-9
msys perl-IO-stringy 2.111-1
msys perl-IPC-Run3 0.048-1
msys perl-JSON 2.97001-1
msys perl-LWP-MediaTypes 6.02-2
msys perl-LWP-Protocol-https 6.07-1
msys perl-List-MoreUtils 0.428-1
msys perl-List-MoreUtils-XS 0.428-2
msys perl-Locale-Gettext 1.07-3
msys perl-MIME-Charset 1.012.2-1
msys perl-MIME-tools 5.509-1
msys perl-MailTools 2.20-1
msys perl-Math-Int64 0.54-2
msys perl-Module-Build 0.4224-1
msys perl-Mozilla-CA 20180117-1
msys perl-Net-DNS 1.16-1
msys perl-Net-HTTP 6.18-1
msys perl-Net-IP 1.26-2
msys perl-Net-SMTP-SSL 1.04-1
msys perl-Net-SSLeay 1.85-1
msys perl-Path-Class 0.37-1
msys perl-Probe-Perl 0.03-2
msys perl-Regexp-Common 2017060201-1
msys perl-Socket6 0.28-3
msys perl-Sort-Versions 1.62-1
msys perl-Spiffy 0.46-1
msys perl-Sys-CPU 0.61-5
msys perl-TAP-Harness-Archive 0.18-1
msys perl-TermReadKey 2.37-3
msys perl-Test-Base 0.89-1
msys perl-Test-Deep 1.128-1
msys perl-Test-Fatal 0.014-1
msys perl-Test-Harness 3.39-1
msys perl-Test-Needs 0.002005-1
msys perl-Test-NoWarnings 1.04-1
msys perl-Test-Pod 1.52-1
msys perl-Test-Requiresinternet 0.05-1
msys perl-Test-Script 1.23-1
msys perl-Test-Simple 1.302122-1
msys perl-Test-YAML 1.07-1
msys perl-Text-CharWidth 0.04-3
msys perl-Text-Diff 1.45-1
msys perl-Text-WrapI18N 0.06-1
msys perl-TimeDate 2.30-2
msys perl-Try-Tiny 0.30-1
msys perl-URI 1.74-1
msys perl-Unicode-GCString 2018.003-1
msys perl-WWW-RobotRules 6.02-2
msys perl-XML-LibXML 2.0132-2
msys perl-XML-NamespaceSupport 1.12-1
msys perl-XML-Parser 2.44-4
msys perl-XML-SAX 1.00-1
msys perl-XML-SAX-Base 1.09-1
msys perl-XML-Simple 2.25-1
msys perl-YAML 1.26-1
msys perl-YAML-Syck 1.30-2
msys perl-YAML-Tiny 1.73-1
msys perl-ack 2.24-1
msys perl-common-sense 3.74-1
msys perl-inc-latest 0.500-1
msys perl-libwww 6.33-1
msys perl-sgmls 1.03ii-1
msys pinentry 1.1.0-2 [installed]
msys pkg-config 0.29.2-1
msys pkgfile 17-1 [installed]
msys po4a 0.54-1
msys procps 3.2.8-2
msys procps-ng 3.3.12-1
msys protobuf 3.6.1-1
msys protobuf-devel 3.6.1-1
msys psmisc 22.21-2
msys publicsuffix-list 20180307.654.ae33511-1
msys pv 1.6.6-1
msys pwgen 2.08-1
msys python 3.6.6-1
msys python-brotli 1.0.5-2
msys python2 2.7.15-2
msys python2-appdirs 1.4.3-2
msys python2-beaker 1.10.0-1
msys python2-brotli 1.0.5-2
msys python2-colorama 0.3.9-2
msys python2-distutils-extra 2.39-1
msys python2-fastimport 0.9.8-1
msys python2-mako 1.0.7-2
msys python2-markupsafe 1.0-2
msys python2-mock 1.0.1-2
msys python2-nose 1.3.7-3
msys python2-packaging 16.8-4
msys python2-pip 10.0.1-1
msys python2-py 1.4.34-1
msys python2-pyalpm 0.8-3
msys python2-pygments 2.2.0-1
msys python2-pyparsing 2.2.0-3
msys python2-pytest 3.2.1-1
msys python2-setuptools 40.0.0-1
msys python2-setuptools-scm 2.1.0-1
msys python2-six 1.10.0-5
msys python3-appdirs 1.4.3-2
msys python3-beaker 1.10.0-1
msys python3-colorama 0.3.9-2
msys python3-distutils-extra 2.39-1
msys python3-mako 1.0.7-2
msys python3-markupsafe 1.0-2
msys python3-mock 1.0.1-2
msys python3-nose 1.3.7-3
msys python3-packaging 16.8-4
msys python3-pip 10.0.1-1
msys python3-py 1.4.34-1
msys python3-pyalpm 0.8-3
msys python3-pygments 2.2.0-1
msys python3-pyparsing 2.2.0-3
msys python3-pytest 3.2.1-1
msys python3-setuptools 40.0.0-1
msys python3-setuptools-scm 2.1.0-1
msys python3-six 1.10.0-5
msys quilt 0.65-2
msys rarian 0.8.1-1
msys rcs 5.9.4-2
msys re2c 1.0.3-1
msys rebase 4.4.4-1 [installed]
msys remake-git 4.1.2957.e3e34dd9-1
msys rhash 1.3.6-1
msys rsync 3.1.3-1
msys rsync2 3.1.3dev_msys2.7.0_r3-0
msys ruby 2.4.0-2
msys ruby-docs 2.4.0-2
msys scons 3.0.1-1
msys screenfetch 3.8.0-1
msys sed 4.5-1 [installed]
msys setconf 0.7.5-1
msys sgml-common 0.6.3-1
msys sharutils 4.15.2-1
msys socat 1.7.3.2-1
msys sqlite 3.21.0-4
msys sqlite-doc 3.21.0-4
msys ssh-pageant-git 1.4.12.g6f47092-1
msys sshpass 1.06-1
msys subversion 1.10.2-1
msys swig 3.0.12-1
msys tar 1.30-1 [installed]
msys task 2.5.1-2
msys tcl 8.6.8-1
msys tcsh 6.20.00-2
msys termbox 1.1.0-2
msys texinfo 6.5-2
msys texinfo-tex 6.5-2
msys tftp-hpa 5.2-2 [installed]
msys tig 2.4.1-1
msys time 1.9-1 [installed]
msys tio 1.31-1
msys tmux 2.7-1
msys tree 1.7.0-1
msys ttyrec 1.0.8-2 [installed]
msys txt2html 2.5201-1
msys txt2tags 2.6-5
msys tzcode 2018.c-1 [installed]
msys ucl 1.03-2
msys ucl-devel 1.03-2
msys unrar 5.6.6-1
msys unzip 6.0-2
msys upx 3.94-1
msys util-linux 2.26.2-1 [installed]
msys util-macros 1.19.2-1
msys vifm 0.9.1-1
msys vim 8.1.0022-1
msys vimpager 2.06-1
msys vimpager-git r279.bc5548d-1
msys w3m 0.5.3-2
msys wcd 6.0.2-1
msys wget 1.19.5-1 [installed]
msys which 2.21-2 [installed]
msys whois 5.3.2-1
msys windows-default-manifest 6.4-1
msys winln 1.1-1
msys winpty 0.4.3-1
msys xdelta3 3.1.0-1
msys xmlto 0.0.28-2
msys xorriso 1.4.8-1
msys xproto 7.0.26-1
msys xz 5.2.4-1 [installed]
msys yasm 1.3.0-2
msys yasm-devel 1.3.0-2
msys yelp-tools 3.28.0-1
msys yelp-xsl 3.28.0-1
msys yodl 4.01.00-1
msys zip 3.0-3
msys zlib 1.2.11-1 [installed]
msys zlib-devel 1.2.11-1
msys znc-git r4812.15ccaca4-1
msys zsh 5.6.1-1
msys zsh-doc 5.6.1-1
dkp-libs 3ds-bulletphysics 2.87-2
dkp-libs 3ds-bzip2 1.0.6-2
dkp-libs 3ds-curl 7.59.0-2
dkp-libs 3ds-examples 20180513-2
dkp-libs 3ds-flite 2.1-1
dkp-libs 3ds-freetype 2.9-1
dkp-libs 3ds-jansson 2.11-1
dkp-libs 3ds-libarchive 3.1.2-2
dkp-libs 3ds-libconfig 1.7.2-1
dkp-libs 3ds-libid3tag 0.15.1b-1
dkp-libs 3ds-libjpeg-turbo 1.5.3-1
dkp-libs 3ds-liblzma 5.2.3-1
dkp-libs 3ds-libmad 0.15.1b-1
dkp-libs 3ds-libogg 1.3.3-2
dkp-libs 3ds-libpng 1.6.34-1
dkp-libs 3ds-libvorbisidec 1.2.1-2
dkp-libs 3ds-mbedtls 2.8.0-1
dkp-libs 3ds-mikmod 3.3.11.1-1
dkp-libs 3ds-mpg123 1.25.10-1
dkp-libs 3ds-pkg-config 0.28-2
dkp-libs 3ds-sdl 1.2.15-4
dkp-libs 3ds-sdl_gfx 2.0.25-1
dkp-libs 3ds-sdl_image 1.2.12-1
dkp-libs 3ds-sdl_mixer 1.2.12-7
dkp-libs 3ds-sdl_ttf 2.0.11-1
dkp-libs 3ds-tinyxml2 6.0.0-1
dkp-libs 3ds-zlib 1.2.11-1
dkp-libs citro2d 1.0.0-1
dkp-libs citro3d 1.4.0-1
dkp-libs default-arm7 0.7.4-2
dkp-libs devkitpro-pkgbuild-helpers 1.0.6-1
dkp-libs dswifi 0.4.2-1
dkp-libs gamecube-examples 20180910-1
dkp-libs gba-examples 20170228-3
dkp-libs gp32-examples 20051021-2
dkp-libs libctru 1.5.0-1
dkp-libs libfat-gba 1.1.3-1
dkp-libs libfat-nds 1.1.3-1
dkp-libs libfat-ogc 1.1.3-1
dkp-libs libfilesystem 0.9.14-1
dkp-libs libgba 0.5.1-1
dkp-libs libmirko 0.9.8-1
dkp-libs libnds 1.7.3-1
dkp-libs libnx 1.4.1-1 [installed]
dkp-libs libogc 1.8.20-1
dkp-libs libtonc 1.4.3-2
dkp-libs maxmod-gba 1.0.11-1
dkp-libs maxmod-nds 1.0.11-2
dkp-libs nds-examples 20180516-2
dkp-libs ppc-bzip2 1.0.6-1
dkp-libs ppc-freetype 2.9-3
dkp-libs ppc-libjpeg-turbo 1.5.3-1
dkp-libs ppc-libogg 1.3.3-2
dkp-libs ppc-libpng 1.6.34-1
dkp-libs ppc-libvorbisidec 1.2.1-1
dkp-libs ppc-mpg123 1.25.10-1
dkp-libs ppc-mxml 2.11-1
dkp-libs ppc-pkg-config 0.28-3
dkp-libs ppc-zlib 1.2.11-1
dkp-libs switch-bulletphysics 2.87-1
dkp-libs switch-bzip2 1.0.6-2 [installed]
dkp-libs switch-curl 7.59.0-1
dkp-libs switch-examples 20180918-1 [installed]
dkp-libs switch-flac 1.3.2-1
dkp-libs switch-freetype 2.9-3 [installed]
dkp-libs switch-glad 0.1.27-1
dkp-libs switch-glm 0.9.9.1-1
dkp-libs switch-jansson 2.11-1
dkp-libs switch-libass 0.14.0-1
dkp-libs switch-libconfig 1.7.2-1
dkp-libs switch-libdrm_nouveau 0.2.1-1
dkp-libs switch-libexpat 2.2.5-1
dkp-libs switch-libfribidi 1.0.4-1
dkp-libs switch-libjpeg-turbo 1.5.3-1 [installed]
dkp-libs switch-libjson-c 0.13.1-1
dkp-libs switch-libmad 0.15.1b-1
dkp-libs switch-libmikmod 3.3.11.1-1
dkp-libs switch-libmodplug 0.8.8.5-1
dkp-libs switch-libogg 1.3.3-1
dkp-libs switch-libopus 1.2.1-1
dkp-libs switch-libpng 1.6.34-3 [installed]
dkp-libs switch-libsamplerate 0.1.9-1
dkp-libs switch-libtheora 1.1.1-1
dkp-libs switch-libvorbis 1.3.5-1
dkp-libs switch-libvorbisidec 1.2.1-1
dkp-libs switch-libxml2 2.9.8-1
dkp-libs switch-mesa 18.2_beta-1
dkp-libs switch-mpg123 1.25.10-2
dkp-libs switch-pkg-config 0.28-2
dkp-libs switch-sdl2 2.0.8-9 [installed]
dkp-libs switch-sdl2_gfx 1.0.4-1 [installed]
dkp-libs switch-sdl2_image 2.0.3-3 [installed]
dkp-libs switch-sdl2_mixer 2.0.2-2
dkp-libs switch-sdl2_net 2.0.1-1
dkp-libs switch-sdl2_ttf 2.0.14-2 [installed]
dkp-libs switch-zlib 1.2.11-1 [installed]
dkp-libs wii-examples 20180910-1
dkp-windows 3dslink 0.5.2-2
dkp-windows 3dstools 1.1.4-2
dkp-windows devkitA64 r12-2 [installed]
dkp-windows devkitARM r49-2
dkp-windows devkitPPC r32-1
dkp-windows devkitpro-keyring r1.787e015-2 [installed]
dkp-windows dstools 1.2.1-1
dkp-windows freeimage-dll 3.17.0-1
dkp-windows gamecube-tools 1.0.2-1
dkp-windows gba-tools 1.2.0-1
dkp-windows general-tools 1.0.2-2 [installed]
dkp-windows gp32-tools 1.0.3-1
dkp-windows grit 0.8.15-1
dkp-windows libusb-dll 1.0.20-1
dkp-windows mmutil 1.8.7-1
dkp-windows ndstool 2.1.2-1
dkp-windows picasso 2.7.0-1
dkp-windows switch-tools 1.4.1-3 [installed]
dkp-windows tex3ds 1.0.1-1
dkp-windows tool-dlls 1.0-1 [installed]
dkp-windows wiiload 0.5.1-1

Thanks!

**Comment by lantus** [comment]
working on a fix now. problem is #define BIT() is also in common.h

**Comment by lantus** [comment]
fixed , please pull/compile latest :)
