### ISSUE TITLE
Flickering screen after loading a game (Rom)

### ISSUE THREAD

**Issue by SUPER-DAN** [lantus/mame-nx#6]
Hi again,

I have compiled the version from yesterday successfully, however, when loading a rom, example Mortal Kombat 2, the "Loading uj22-vid (20 / 20) stays on the screen and do not disapear.. causing the screen to flicker.  I can see when it loads "Loading complete", but it comes back to "Loading "nbauj23.bin (21/21) for NBA Jam for example.  It has to be about that loading output on screen.  Otherwise, the speed of this new version seems fine.  But it's unplayable like that.  Thanks

**Comment by lantus** [comment]
yes confirmed. I will look at it

**Comment by lantus** [comment]
should be fixed. Pull latest and let me know

**Comment by SUPER-DAN** [comment]
Thanks that worked!   I also added button ZL and ZR as button option.  I'll try to suggest the new code (sorry for time using github). Thanks again!!

**Comment by SUPER-DAN** [comment]
if you exit the game and go back into another game or the same one, the flickering still exit.. and when clicking "exit" button, it loads the last game :(  Sorry

**Comment by lantus** [comment]
no problem - will look at it now

**Comment by lantus** [comment]
can you try this .nro and see it if fixes - https://drive.google.com/open?id=1y3jLY68xCj8rjyFscBPHAaj42GhXOh09

if it does i will check the code in. Im using an emulator to test and not a real switch right now.

thanks

**Comment by SUPER-DAN** [comment]
It crashes when I tried to exit the game.  Minus + Plus button.  Coudln't get to the main menu at all.  Just for you information, I couldn't replicate the flickering anymore with the latest build from the github.  So that's fine I think or maybe I trigger something I can't trigger again :)

**Comment by lantus** [comment]
Ok great. Keep testing it and let me know if it occurs again. Going to close this issue for now
