### ISSUE TITLE
Multiple Sound FX at same time slowing down the game

### ISSUE THREAD

**Issue by SUPER-DAN** [lantus/mame-nx#8]
Hi, since OpenGL(I think), the graphics(colors and crispness) are way better, however it seems that when multiple sound fx are introduce in the game major slowdown(decrease in FPS and choppy sound) can be felt.  This can be reproduce in either Mortal Kombat 2 or UMK3 with any characters throwing their special lasers or flames.  I don't know if it's related to multiple sound(DCS audio?) or because of too many layers of graphics. I'll try to re-download the first release and test with it to see if it's something new introduced. Is there a way to debug and disable sound to test if it's the problem?   So so close I can smell it!!

**Comment by lantus** [comment]
let me know how the original release is. If something new was introduced causing the slowdown it can be addressed

**Comment by lantus** [comment]
fixed in 2.2 - https://github.com/lantus/mame-nx/releases/tag/2.2
